accepted = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "Zlib",
    "ISC",
    "MPL-2.0",
    "BSL-1.0",
    "Ubuntu-font-1.0",
    "OFL-1.1",
    "NCSA",
    "Apache-2.0 WITH LLVM-exception"

]

no-clearly-defined = true
